package eu.midnightdust.motschen.verticalslabs;

import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.fabricmc.fabric.api.client.itemgroup.FabricItemGroupBuilder;
import net.fabricmc.fabric.api.tool.attribute.v1.FabricToolTags;
import net.minecraft.block.Block;
import net.minecraft.block.Material;
import net.minecraft.item.*;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

public class VerticalSlabs implements ModInitializer {

    public static final String MOD_ID = "verticalslabs";
    public static final ItemGroup VerticalSlabsGroup = FabricItemGroupBuilder.build(new Identifier(MOD_ID, "vertical_slabs"), () -> new ItemStack(VerticalSlabs.VERTICAL_OAK_SLAB));
    public static final Block VERTICAL_OAK_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.WOOD).sounds(BlockSoundGroup.WOOD).hardness(2f).breakByTool(FabricToolTags.AXES));
    public static final Block VERTICAL_SPRUCE_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.WOOD).sounds(BlockSoundGroup.WOOD).hardness(2f).breakByTool(FabricToolTags.AXES));
    public static final Block VERTICAL_BIRCH_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.WOOD).sounds(BlockSoundGroup.WOOD).hardness(2f).breakByTool(FabricToolTags.AXES));
    public static final Block VERTICAL_JUNGLE_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.WOOD).sounds(BlockSoundGroup.WOOD).hardness(2f).breakByTool(FabricToolTags.AXES));
    public static final Block VERTICAL_ACACIA_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.WOOD).sounds(BlockSoundGroup.WOOD).hardness(2f).breakByTool(FabricToolTags.AXES));
    public static final Block VERTICAL_DARK_OAK_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.WOOD).sounds(BlockSoundGroup.WOOD).hardness(2f).breakByTool(FabricToolTags.AXES));
    public static final Block VERTICAL_CRIMSON_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.WOOD).sounds(BlockSoundGroup.WOOD).hardness(2f).breakByTool(FabricToolTags.AXES));
    public static final Block VERTICAL_WARPED_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.WOOD).sounds(BlockSoundGroup.WOOD).hardness(2f).breakByTool(FabricToolTags.AXES));
    public static final Block VERTICAL_STONE_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_SMOOTH_STONE_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_SANDSTONE_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_CUT_SANDSTONE_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_COBBLESTONE_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_BRICK_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_STONE_BRICK_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_NETHER_BRICK_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_QUARTZ_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_RED_SANDSTONE_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_CUT_RED_SANDSTONE_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_PURPUR_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_PRISMARINE_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_PRISMARINE_BRICK_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_DARK_PRISMARINE_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_POLISHED_GRANITE_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_SMOOTH_RED_SANDSTONE_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_MOSSY_STONE_BRICK_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_POLISHED_DIORITE_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_MOSSY_COBBLESTONE_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_END_STONE_BRICK_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_SMOOTH_SANDSTONE_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_SMOOTH_QUARTZ_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_GRANITE_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_ANDESITE_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_RED_NETHER_BRICK_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_POLISHED_ANDESITE_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_DIORITE_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_BLACKSTONE_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_POLISHED_BLACKSTONE_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));
    public static final Block VERTICAL_POLISHED_BLACKSTONE_BRICK_SLAB = new VerticalSlab(FabricBlockSettings.of(Material.STONE).sounds(BlockSoundGroup.STONE).hardness(2f).breakByHand(false).breakByTool(FabricToolTags.PICKAXES));

    @Override
    public void onInitialize() {
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_oak_slab"), VERTICAL_OAK_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_oak_slab"), new BlockItem(VERTICAL_OAK_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_spruce_slab"), VERTICAL_SPRUCE_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_spruce_slab"), new BlockItem(VERTICAL_SPRUCE_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_birch_slab"), VERTICAL_BIRCH_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_birch_slab"), new BlockItem(VERTICAL_BIRCH_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_jungle_slab"), VERTICAL_JUNGLE_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_jungle_slab"), new BlockItem(VERTICAL_JUNGLE_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_acacia_slab"), VERTICAL_ACACIA_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_acacia_slab"), new BlockItem(VERTICAL_ACACIA_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_dark_oak_slab"), VERTICAL_DARK_OAK_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_dark_oak_slab"), new BlockItem(VERTICAL_DARK_OAK_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_crimson_slab"), VERTICAL_CRIMSON_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_crimson_slab"), new BlockItem(VERTICAL_CRIMSON_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_warped_slab"), VERTICAL_WARPED_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_warped_slab"), new BlockItem(VERTICAL_WARPED_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_stone_slab"), VERTICAL_STONE_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_stone_slab"), new BlockItem(VERTICAL_STONE_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_smooth_stone_slab"), VERTICAL_SMOOTH_STONE_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_smooth_stone_slab"), new BlockItem(VERTICAL_SMOOTH_STONE_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_sandstone_slab"), VERTICAL_SANDSTONE_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_sandstone_slab"), new BlockItem(VERTICAL_SANDSTONE_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_cut_sandstone_slab"), VERTICAL_CUT_SANDSTONE_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_cut_sandstone_slab"), new BlockItem(VERTICAL_CUT_SANDSTONE_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_cobblestone_slab"), VERTICAL_COBBLESTONE_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_cobblestone_slab"), new BlockItem(VERTICAL_COBBLESTONE_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_brick_slab"), VERTICAL_BRICK_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_brick_slab"), new BlockItem(VERTICAL_BRICK_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_stone_brick_slab"), VERTICAL_STONE_BRICK_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_stone_brick_slab"), new BlockItem(VERTICAL_STONE_BRICK_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_nether_brick_slab"), VERTICAL_NETHER_BRICK_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_nether_brick_slab"), new BlockItem(VERTICAL_NETHER_BRICK_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_quartz_slab"), VERTICAL_QUARTZ_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_quartz_slab"), new BlockItem(VERTICAL_QUARTZ_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_red_sandstone_slab"), VERTICAL_RED_SANDSTONE_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_red_sandstone_slab"), new BlockItem(VERTICAL_RED_SANDSTONE_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_cut_red_sandstone_slab"), VERTICAL_CUT_RED_SANDSTONE_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_cut_red_sandstone_slab"), new BlockItem(VERTICAL_CUT_RED_SANDSTONE_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_purpur_slab"), VERTICAL_PURPUR_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_purpur_slab"), new BlockItem(VERTICAL_PURPUR_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_prismarine_slab"), VERTICAL_PRISMARINE_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_prismarine_slab"), new BlockItem(VERTICAL_PRISMARINE_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_prismarine_brick_slab"), VERTICAL_PRISMARINE_BRICK_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_prismarine_brick_slab"), new BlockItem(VERTICAL_PRISMARINE_BRICK_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_dark_prismarine_slab"), VERTICAL_DARK_PRISMARINE_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_dark_prismarine_slab"), new BlockItem(VERTICAL_DARK_PRISMARINE_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_polished_granite_slab"), VERTICAL_POLISHED_GRANITE_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_polished_granite_slab"), new BlockItem(VERTICAL_POLISHED_GRANITE_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_smooth_red_sandstone_slab"), VERTICAL_SMOOTH_RED_SANDSTONE_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_smooth_red_sandstone_slab"), new BlockItem(VERTICAL_SMOOTH_RED_SANDSTONE_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_mossy_stone_brick_slab"), VERTICAL_MOSSY_STONE_BRICK_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_mossy_stone_brick_slab"), new BlockItem(VERTICAL_MOSSY_STONE_BRICK_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_polished_diorite_slab"), VERTICAL_POLISHED_DIORITE_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_polished_diorite_slab"), new BlockItem(VERTICAL_POLISHED_DIORITE_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_mossy_cobblestone_slab"), VERTICAL_MOSSY_COBBLESTONE_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_mossy_cobblestone_slab"), new BlockItem(VERTICAL_MOSSY_COBBLESTONE_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_end_stone_brick_slab"), VERTICAL_END_STONE_BRICK_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_end_stone_brick_slab"), new BlockItem(VERTICAL_END_STONE_BRICK_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_smooth_sandstone_slab"), VERTICAL_SMOOTH_SANDSTONE_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_smooth_sandstone_slab"), new BlockItem(VERTICAL_SMOOTH_SANDSTONE_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_smooth_quartz_slab"), VERTICAL_SMOOTH_QUARTZ_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_smooth_quartz_slab"), new BlockItem(VERTICAL_SMOOTH_QUARTZ_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_granite_slab"), VERTICAL_GRANITE_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_granite_slab"), new BlockItem(VERTICAL_GRANITE_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_andesite_slab"), VERTICAL_ANDESITE_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_andesite_slab"), new BlockItem(VERTICAL_ANDESITE_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_red_nether_brick_slab"), VERTICAL_RED_NETHER_BRICK_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_red_nether_brick_slab"), new BlockItem(VERTICAL_RED_NETHER_BRICK_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_polished_andesite_slab"), VERTICAL_POLISHED_ANDESITE_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_polished_andesite_slab"), new BlockItem(VERTICAL_POLISHED_ANDESITE_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_diorite_slab"), VERTICAL_DIORITE_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_diorite_slab"), new BlockItem(VERTICAL_DIORITE_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_blackstone_slab"), VERTICAL_BLACKSTONE_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_blackstone_slab"), new BlockItem(VERTICAL_BLACKSTONE_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_polished_blackstone_slab"), VERTICAL_POLISHED_BLACKSTONE_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_polished_blackstone_slab"), new BlockItem(VERTICAL_POLISHED_BLACKSTONE_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
        Registry.register(Registry.BLOCK, new Identifier("verticalslabs","vertical_polished_blackstone_brick_slab"), VERTICAL_POLISHED_BLACKSTONE_BRICK_SLAB);
        Registry.register(Registry.ITEM, new Identifier("verticalslabs","vertical_polished_blackstone_brick_slab"), new BlockItem(VERTICAL_POLISHED_BLACKSTONE_BRICK_SLAB, new Item.Settings().group(VerticalSlabs.VerticalSlabsGroup)));
    }
}
